# Generated by Django 5.0.6 on 2024-06-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articles_slug_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='featured_image',
            field=models.URLField(default='https://dummyimage.com/700x350/343a40/6c757d', max_length=512),
        ),
    ]
